name: the_algorithms_dart

repository: https://github.com/TheAlgorithms/Dart

dependencies:
  test: ^1.15.4
  coverage: ^1.6.0

dev_dependencies:
  stack: ^0.2.1

environment:
  sdk: ">=2.12.0 <3.0.0"
