name: dart_test_analyze_format
on: [push, pull_request]
jobs:
  dart_test_analyze_format:
    runs-on: ubuntu-latest
    container: google/dart
    steps:
      - uses: actions/checkout@v2
      - run: (echo 'deb http://deb.debian.org/debian buster main contrib non-free') > /etc/apt/sources.list.d/buster.list
      - run: apt-get update
      - run: apt-get install --no-install-recommends -y -q lcov
      - run: dart pub get
      - run: dart test --coverage .
      - run: dart pub run coverage:format_coverage -i . -l > coverage.lcov
      - run: lcov -l coverage.lcov
      - run: dart analyze
      - run: dart format --set-exit-if-changed .
