name: dart_test_analyze_format
on: [push, pull_request]
jobs:
  dart_test_analyze_format:
    runs-on: ubuntu-latest
    container: google/dart
    steps:
      - uses: actions/checkout@v2
      - run: dart pub get
      - run: dart test data_structures/linked_list.dart
      - run: dart analyze
      - run: dart format --set-exit-if-changed .
      - uses: actions/setup-python@v2
      - run: pip install codespell
      - run: codespell --quiet-level=2 || true  # --ignore-words-list="" --skip=""
